optional parameter
Tyrrrz/CliFx pull request #119
Opened 2022-01-06 02:29 UTC by alirezanet

This PR adds `IsRequired` to `CommandParameter`, but only can be false if the parameter is the last one.
Analyzer will check this behavior

Related to #99 #76

2022-01-09 16:40 UTC, Tyrrrz requested changes

2022-01-09 16:40 UTC, Tyrrrz commented on CliFx.Analyzers/ParameterMustBeRequiredExceptLastOneAnalyzer.cs
> +        if (parameter is null || parameter.IsRequired is null or true )
```suggestion
        if (parameter is null || parameter.IsRequired != false)
```

2022-01-09 16:40 UTC, Tyrrrz commented on CliFx.Analyzers/ObjectModel/CommandParameterSymbol.cs
> +    public CommandParameterSymbol(int order,
```suggestion
    public CommandParameterSymbol(
        int order,
```

2022-01-09 16:40 UTC, Tyrrrz commented on CliFx.Analyzers/ObjectModel/CommandParameterSymbol.cs
> +        return attribute is null ? null : FromAttribute(attribute);
```suggestion
        return attribute is not null
            ? FromAttribute(attribute)
            : null;
```

2022-01-09 16:40 UTC, Tyrrrz commented on CliFx/Attributes/CommandParameterAttribute.cs
> +    /// If an parameter is required, the user will get an error if they don't set it.
```suggestion
    /// If a parameter is required, the user will get an error if they don't set it.
```

2022-01-09 16:40 UTC, Tyrrrz commented on CliFx/Attributes/CommandParameterAttribute.cs
> +    /// Only the last CommandParameter can be optional.
```suggestion
    /// Only the last parameter in order can be optional.
```

2022-01-09 16:40 UTC, Tyrrrz commented on CliFx/CommandBinder.cs
>                  "Missing parameter(s):" +
```suggestion
                "Missing required parameter(s):" +
```

2022-01-09 16:40 UTC, Tyrrrz commented on CliFx/Formatting/HelpConsoleFormatter.cs
> +            Write(ConsoleColor.Red, star);
```suggestion
            if (parameterSchema.IsRequired)
            {
                Write(ConsoleColor.Red, "* ");
            }
            else
            {
                WriteHorizontalMargin();
            }
```

2022-01-09 16:40 UTC, Tyrrrz commented on CliFx/Schema/ParameterSchema.cs
>      public string GetFormattedIdentifier() => Property.IsScalar()
```suggestion
    public string GetFormattedIdentifier() => Property.IsScalar()
```

2022-01-09 16:40 UTC, Tyrrrz commented on CliFx.Analyzers/ParameterMustBeRequiredExceptLastOneAnalyzer.cs
> +    public ParameterMustBeRequiredExceptLastOneAnalyzer()
Also rename file and test class
(for consistency with the non-scalar analyzer)

```suggestion
public class ParameterMustBeLastIfNotRequiredAnalyzer : AnalyzerBase
{
    public ParameterMustBeLastIfNotRequiredAnalyzer()
```

2022-01-10 04:18 UTC, alirezanet commented
Error is related to my other PL. 

I'll send another PL to fix the line break issue on Linux:

![image](https://user-images.githubusercontent.com/7004080/148717904-367f2f4c-8ee5-4143-9a75-603305a8dbb5.png)

2022-01-10 21:04 UTC, Tyrrrz commented on CliFx/Formatting/HelpConsoleFormatter.cs
> +            }
```suggestion
            }

```

2022-01-10 21:10 UTC, Tyrrrz approved these changes

2022-01-10 21:11 UTC, merged

2022-01-10 21:11 UTC, Tyrrrz commented
Thanks!